# permissions for end users to edit clustermeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermeta-editor-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - clustermeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - clustermeta/status
  verbs:
  - get
