apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: public-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - managerstates
  verbs:
  - get
  - list
  - watch
