# permissions for end users to edit trafficpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trafficpolicy-editor-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - trafficpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - trafficpolicies/status
  verbs:
  - get
