# permissions for end users to edit virtualapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualapp-editor-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualapps/status
  verbs:
  - get
