# permissions for end users to view virtualapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualapp-viewer-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualapps/status
  verbs:
  - get
